import React from 'react';
import SpeciesCard from './Cards/SpeciesCard';
import RiskCard from './Cards/RiskCard';
import FirstAidCard from './Cards/FirstAidCard';
import KnowledgeCard from './Cards/KnowledgeCard';

export default function ReportDashboard({ payload, uploadedImageUrl, onReset }) {
  if (!payload) return null;

  const { card_species, card_risk, card_first_aid, card_knowledge } = payload;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      {/* Top Banner Control */}
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderBottom: '1px solid rgba(255,255,255,0.06)',
        paddingBottom: '0.75rem'
      }}>
        <div>
          <h2 style={{ fontSize: '1.25rem', fontWeight: 800 }}>Analysis Report</h2>
          <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Generated by Multi-Agent Coordinator</p>
        </div>
        
        <button
          onClick={onReset}
          className="btn btn-secondary"
          style={{ padding: '0.45rem 1rem', fontSize: '0.8rem' }}
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M23 4v6h-6"/>
            <path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10"/>
          </svg>
          Reset View
        </button>
      </div>

      {/* Grid Layout of Report Cards */}
      <div style={{
        display: 'flex',
        flexDirection: 'column',
        gap: '1.5rem'
      }}>
        {/* Row 1: Identification & Risk side-by-side or stacked */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: '1fr',
          gap: '1.5rem'
        }}>
          <SpeciesCard data={card_species} uploadedImageUrl={uploadedImageUrl} />
          
          <RiskCard data={card_risk} />
        </div>

        {/* Row 2: Emergency First Aid (Rendered prominent, especially for dangerous creatures) */}
        {card_first_aid && (
          <FirstAidCard data={card_first_aid} />
        )}

        {/* Row 3: Ecological Facts & Bio */}
        {card_knowledge && (
          <KnowledgeCard data={card_knowledge} />
        )}
      </div>
    </div>
  );
}
