import os
import uuid
from django.db import models

class AnalysisSession(models.Model):
    """
    Represents an upload and analysis session initiated by a user.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    image = models.ImageField(upload_to='uploads/%Y/%m/%d/', max_length=500)
    user_description = models.TextField(null=True, blank=True)
    latency_ms = models.IntegerField(null=True, blank=True)
    status = models.CharField(
        max_length=20,
        choices=[
            ('success', 'Success'),
            ('partial_success', 'Partial Success'),
            ('error', 'Error'),
        ],
        default='success'
    )

    def __str__(self):
        return f"Session {self.id} ({self.created_at.strftime('%Y-%m-%d %H:%M:%S')})"



class AnalysisResult(models.Model):
    """
    Holds the consolidated output generated by all sub-agents.
    """
    session = models.OneToOneField(
        AnalysisSession,
        on_delete=models.CASCADE,
        related_name='result'
    )
    common_name = models.CharField(max_length=255)
    scientific_name = models.CharField(max_length=255)
    confidence = models.FloatField()
    risk_rating = models.CharField(
        max_length=20,
        choices=[
            ('Critical', 'Critical'),
            ('High', 'High'),
            ('Medium', 'Medium'),
            ('Low', 'Low'),
        ]
    )
    primary_hazard = models.CharField(max_length=255)
    
    # Store first aid (warnings, checklists, disclaimer) and general facts directly as JSON
    first_aid_payload = models.JSONField()
    knowledge_payload = models.JSONField()
    verification_notes = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"Result: {self.common_name} ({self.risk_rating})"


from django.db.models.signals import post_delete
from django.dispatch import receiver

@receiver(post_delete, sender=AnalysisSession)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes image file from filesystem when corresponding AnalysisSession object is deleted.
    """
    if instance.image:
        try:
            if os.path.isfile(instance.image.path):
                os.remove(instance.image.path)
        except Exception:
            pass
