# Generated by Django 4.2.30 on 2026-07-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_analysisresult_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysissession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
