# Generated by Django 4.2.30 on 2026-07-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_alter_analysissession_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysissession',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='analysissession',
            name='longitude',
        ),
    ]
